version: "3.8"

services:
  web:
    restart: always
    container_name: gendoc
    build: .
    ports:
      - 8085:80
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: "300M"
          pids: 100
